### ISSUE TITLE
TypeScript error when compiling

### ISSUE THREAD

**Issue by anon1352** [cutechan/cutechan#3]
All dependencies are installed and present. The system is running on Debian 9, user is root.

When compiling first time, gives an error like "no go files found in go/src/kpopnet" but it dissappeared on the second try (I assume it downloaded necessary files).

Still, it gives some errors during compilation. Here's the output:

        root@server:/var/aib/kpop# make
        /var/aib/kpop/node_modules/.bin/gulp smiles
        [16:18:52] Using gulpfile /var/aib/kpop/gulpfile.js
        [16:18:52] Starting 'smiles'...
        [16:19:11] Finished 'smiles' after 18 s
        /var/aib/kpop/node_modules/.bin/gulp
        [16:19:13] Using gulpfile /var/aib/kpop/gulpfile.js
        [16:19:13] Starting 'default'...
        [16:19:13] Starting 'clean'...
        [16:19:13] Finished 'clean' after 23 ms
        [16:19:13] Starting 'labels'...
        [16:19:14] Finished 'labels' after 1.19 s
        [16:19:14] Starting 'es6'...
        [16:19:16] Starting 'es5'...
        [16:19:16] Starting 'loader'...
        [16:19:16] Starting 'polyfills'...
        [16:19:16] Starting 'css'...
        [16:19:32] Starting 'assets'...
        [16:19:32] Starting 'kpopnet'...
        /var/aib/kpop/node_modules/webpack-cli/bin/config-yargs.js:89
        				describe: optionsSchema.definitions.output.properties.path.description,
        				                                          ^
        TypeError: Cannot read property 'properties' of undefined
            at module.exports (/var/aib/kpop/node_modules/webpack-cli/bin/config-yargs.js:89:47)
            at /var/aib/kpop/node_modules/webpack-cli/bin/webpack.js:60:27
            at Object.<anonymous> (/var/aib/kpop/node_modules/webpack-cli/bin/webpack.js:515:3)
            at Module._compile (module.js:577:32)
            at Object.Module._extensions..js (module.js:586:10)
            at Module.load (module.js:494:32)
            at tryModuleLoad (module.js:453:12)
            at Function.Module._load (module.js:445:3)
            at Module.runMain (module.js:611:10)
            at run (bootstrap_node.js:394:7)
        /var/aib/kpop/gulpfile.js:109
            throw err;
            ^
        TypeScript error: /var/aib/kpop/ts/posts/reply.tsx(942,12): error TS2322: Type '{ children: string; className: string; progress: number; title: string; onClick: () => void; }' is not assignable to type 'Props'.
          Types of property 'children' are incompatible.
            Type 'string' is not assignable to type 'Element'.
            at Object.getError (/var/aib/kpop/node_modules/gulp-typescript/release/utils.js:56:15)
            at Output.getError (/var/aib/kpop/node_modules/gulp-typescript/release/output.js:90:22)
            at Output.diagnostic (/var/aib/kpop/node_modules/gulp-typescript/release/output.js:93:25)
            at ProjectCompiler.reportDiagnostics (/var/aib/kpop/node_modules/gulp-typescript/release/compiler.js:147:33)
            at ProjectCompiler.inputDone (/var/aib/kpop/node_modules/gulp-typescript/release/compiler.js:43:38)
            at CompileStream.end (/var/aib/kpop/node_modules/gulp-typescript/release/project.js:136:31)
            at DestroyableTransform.onend (/var/aib/kpop/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
            at DestroyableTransform.g (events.js:292:16)
            at emitNone (events.js:91:20)
            at DestroyableTransform.emit (events.js:185:7)
        Makefile:37: recipe for target 'client' failed
        make: *** [client] Error 1

Seems like there's a problem with config-yargs.js for webpack, hence the typescript error where he cannot find an object type "Props" (not sure).

Expected behaviour: succesful compilation.
Actual result: error in typescript compilation caused by webpack configuration.
Details/log: provided above.

TIA.

**Comment by Kagami** [comment]
Might be due to some updated dependency. Thanks, I will look into it.

**Comment by Kagami** [comment]
Hi, sorry for the delay.

Please try now. Make sure to remove `node_modules` and `go/src/github.com/Kagami/kpopnet` before running the `make`.
