### ISSUE TITLE
'polyfills' errored after 1.06 s - Error: File not found with singular glob

### ISSUE THREAD

**Issue by sangvinivs** [cutechan/cutechan#8]
Hi, I really like cutechan, but I'm having issues building it on a VPS running Ubuntu 18.04.

This is the error I'm getting:
```
vichan@max:~/cutechan$ make
/home/vichan/cutechan/node_modules/.bin/gulp
[14:22:09] Using gulpfile ~/cutechan/gulpfile.js
[14:22:09] Starting 'default'...
[14:22:09] Starting 'clean'...
[14:22:09] Finished 'clean' after 54 ms
[14:22:09] Starting 'labels'...
[14:22:09] Finished 'labels' after 743 ms
[14:22:09] Starting 'es6'...
[14:22:09] Starting 'es5'...
[14:22:09] Starting 'loader'...
[14:22:09] Starting 'polyfills'...
[14:22:09] Starting 'css'...
[14:22:09] Starting 'assets'...
[14:22:10] 'polyfills' errored after 1.06 s
[14:22:10] Error: File not found with singular glob: /home/vichan/cutechan/node_modules/core-js/client/core.min.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/vichan/cutechan/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob.EventEmitter.emit (domain.js:485:12)
    at Glob._finish (/home/vichan/cutechan/node_modules/glob/glob.js:197:8)
    at done (/home/vichan/cutechan/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/home/vichan/cutechan/node_modules/glob/glob.js:688:12)
    at /home/vichan/cutechan/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/vichan/cutechan/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/home/vichan/cutechan/node_modules/glob/glob.js:764:12)
[14:22:10] 'default' errored after 1.86 s
[14:22:10] The following tasks did not complete: es6, es5, loader, css, assets
[14:22:10] Did you forget to signal async completion?
Makefile:22: recipe for target 'client' failed
make: *** [client] Error 1
```

I'm not sure if I'm doing something wrong on my part or not. I already encountered and solved a bunch of errors during compilation, mostly relating to missing go packages (which I had to manually install from github), as well as one where smiles.go couldn't be found, so I had to manually copy it to its path in go/src from its folder in the cutechan directory, but I'm kinda stuck now, so I was hoping you could shed some light on the situation. 

If it helps, I am also getting this slightly different error each time I try to compile after installing a npm package:
```
vichan@max:~/cutechan$ make
/home/vichan/cutechan/node_modules/.bin/gulp smiles
[14:32:26] Using gulpfile ~/cutechan/gulpfile.js
[14:32:26] Starting 'smiles'...
[14:32:36] Finished 'smiles' after 9.36 s
/home/vichan/cutechan/node_modules/.bin/gulp
[14:32:37] Using gulpfile ~/cutechan/gulpfile.js
[14:32:37] Starting 'default'...
[14:32:37] Starting 'clean'...
[14:32:37] Finished 'clean' after 29 ms
[14:32:37] Starting 'labels'...
[14:32:37] Finished 'labels' after 464 ms
[14:32:37] Starting 'es6'...
[14:32:37] Starting 'es5'...
[14:32:37] Starting 'loader'...
[14:32:37] Starting 'polyfills'...
[14:32:37] Starting 'css'...
[14:32:37] Starting 'assets'...
[14:32:38] 'polyfills' errored after 989 ms
[14:32:38] Error: File not found with singular glob: /home/vichan/cutechan/node_modules/core-js/client/core.min.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/vichan/cutechan/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob.EventEmitter.emit (domain.js:485:12)
    at Glob._finish (/home/vichan/cutechan/node_modules/glob/glob.js:197:8)
    at done (/home/vichan/cutechan/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/home/vichan/cutechan/node_modules/glob/glob.js:688:12)
    at /home/vichan/cutechan/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/vichan/cutechan/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/home/vichan/cutechan/node_modules/glob/glob.js:764:12)
[14:32:38] 'default' errored after 1.49 s
[14:32:38] The following tasks did not complete: es6, es5, loader, css, assets
[14:32:38] Did you forget to signal async completion?
Makefile:22: recipe for target 'client' failed
make: *** [client] Error 1
```

And these are the results from the npm audit:
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ yargs-parser                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp > gulp-cli > yargs > yargs-parser                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1500                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp.spritesmith [dev]                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp.spritesmith > async > lodash                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1523                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 2 low severity vulnerabilities in 848 scanned packages
  2 vulnerabilities require manual review. See the full report for details.
```

Thanks.

**Comment by Kagami** [comment]
Hi,

> I already encountered and solved a bunch of errors during compilation, mostly relating to missing go packages (which I had to manually install from github), as well as one where smiles.go couldn't be found

It should have been handled by Makefile automatically, probably it's a bit buggy.

> File not found with singular glob: /home/vichan/cutechan/node_modules/core-js/client/core.min.js

Try

```bash
ls node_modules/core-js/client/core.min.js
npm install
npm ls core-js
```

**Comment by sangvinivs** [comment]
Just wanted to say that the problem was actually with dependencies not being installed/updated properly. I installed cutechan successfully after having updated them.
